version: '2'

services:
  clonetocloud:
    image: aguamala/clonetocloud:{{ clonetocloud.docker_compose.tag }}
    container_name: clonetocloud
    restart: {{ clonetocloud.docker_compose.restart }}
    volumes:
      - /etc/localtime:/etc/localtime
{% if (clonetocloud_lsyncd is defined and clonetocloud_lsyncd is iterable and clonetocloud_lsyncd|length > 0) %}
      - ./lsyncd.conf:/lsyncd.conf
{% endif %}
{% if (clonetocloud_rclone is defined and clonetocloud_rclone is iterable and clonetocloud_rclone|length > 0) %}
      - ./rclone.cfg:/root/.rclone.cfg
{% endif %}
{% if (clonetocloud.docker_compose.volumes is defined and clonetocloud.docker_compose.volumes is iterable and  clonetocloud.docker_compose.volumes|length > 0) %}
{% for volume in clonetocloud.docker_compose.volumes  %}
      - {{ volume }}
{% endfor %}
{% endif %}
{% for sync in clonetocloud_lsyncd  %}
{% if (sync.volume is defined) %}
      - {{ volume }}
{% endif %}
{% endfor %}

{% if (clonetocloud.docker_compose.volumes_from is defined and clonetocloud.docker_compose.volumes_from is iterable and clonetocloud.docker_compose.volumes_from|length > 0) %}
    volumes_from:
{% for volume in clonetocloud.docker_compose.volumes_from  %}
      - {{ volume }}
{% endfor %}
{% endif %}


{% if (clonetocloud_rclone is undefined) %}
    environment:
      RCLONE_ACCESS_KEY_ID: {{ clonetocloud_rclone_access_key }}
      RCLONE_SECRET_ACCESS_KEY: {{ clonetocloud_rclone_secret_key }}
      RCLONE_TYPE: {{ clonetocloud_rclone_type | default('s3') }}
{% endif %}
{% if (clonetocloud.docker_compose.env_vars is defined and clonetocloud.docker_compose.env_vars is iterable and clonetocloud.docker_compose.env_vars|length > 0) %}
{% for env_var in clonetocloud.docker_compose.env_vars  %}
      - {{ env_var }}
{% endfor %}
{% endif %}

{% if (clonetocloud_docker_compose_network is defined) %}
networks:
  default:
    external:
      name: {{ clonetocloud_docker_compose_network }}
{% endif %}
